# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install isort==4.3.21 pylint flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -m nltk.downloader punkt
    - name: Import ordering with isort
      run: |
        isort
    - name: Lint with pylint
      run: |
        pylint .
    - name: Lint with flake8
      run: |
        flake8
    - name: Test with pytest
      env:
        GOOGLE_CLOUD_API_KEY: ${{secrets.GOOGLE_CLOUD_API_KEY}}
      run: |
        python -m pytest
